name: Docker Image CI

on:
  release:
    types:
      - published

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: GitHub Docker Action
      uses: matootie/github-docker@v2.2.3
      if: github.repository == 'zudvpn/strongswan'
    - name: Create Docker Image
      uses: ./
      with:
        accessToken: ${{ secrets.GITHUB_TOKEN }}
    - name: Docker Image Output
      run: echo ${{ steps.run-action.outputs.imageURL }}
