name: Docker Image CI

on:
  release:
    types:
      - published

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
    - name: Create Docker Image
      uses: matootie/github-docker@v2.2.3
      with:
        accessToken: ${{ secrets.GITHUB_TOKEN }}
    - name: Docker Image Output
      run: echo ${{ steps.run-action.outputs.imageURL }}
